export function getCategory() {
  return Promise.resolve([
    {
      id: 1,
      category: "Beauty",
      subCategory: "Beauty Level 1",
      subCategoryL2: "Beauty Level 2",
      brand: "Parachute Advansed Body Lotion",
      subBrand: "Parachute Advansed Body Lotion",
    },

    {
      id: 2,
      category: "Foods",
      subCategory: "Foods Level 1",
      subCategoryL2: "Foods Level 2",
      brand: "Max Care",
      subBrand: "Max Care",
    },
    {
      id: 3,
      category: "Hair Care",
      subCategory: "Hair Care Level 1",
      subCategoryL2: "Hair Care Level 2",
      brand: "Dabur Amla",
      subBrand: "Dabur Amla",
    },
    {
      id: 4,
      category: "Male Grooming",
      subCategory: "Male Grooming Level 1",
      subCategoryL2: "Male Grooming Level 2",
      brand: "Axe",
      subBrand: "Axe",
    },
    {
      id: 5,
      category: "Beauty",
      subCategory: "Beauty Level 1",
      subCategoryL2: "Beauty Level 2",
      brand: "PureSense",
      subBrand: "PureSense",
    },
    {
      id: 6,
      category: "Beauty",
      subCategory: "Beauty Level 1",
      subCategoryL2: "Beauty Level 2",
      brand: "Livon",
      subBrand: "Livon",
    },
    {
      id: 7,
      category: "Beauty",
      subCategory: "Beauty Level 1",
      subCategoryL2: "Beauty Level 2",
      brand: "Wow",
      subBrand: "Wow",
    },
    {
      id: 8,
      category: "Beauty",
      subCategory: "Beauty Level 1",
      subCategoryL2: "Beauty Level 2",
      brand: "Mama Earth",
      subBrand: "Mama Earth",
    },
    {
      id: 9,
      category: "Male Grooming",
      subCategory: "Male Grooming Level 1",
      subCategoryL2: "Male Grooming Level 2",
      brand: "Beardo",
      subBrand: "Beardo",
    },
    {
      id: 10,
      category: "Male Grooming",
      subCategory: "Male Grooming Level 1",
      subCategoryL2: "Male Grooming Level 2",
      brand: "Parachute Advansed Men",
      subBrand: "Parachute Advansed Men",
    },
    {
      id: 11,
      category: "Male Grooming",
      subCategory: "Male Grooming Level 1",
      subCategoryL2: "Male Grooming Level 2",
      brand: "Set Wet",
      subBrand: "Set Wet",
    },
    {
      id: 12,
      category: "Male Grooming",
      subCategory: "Male Grooming Level 1",
      subCategoryL2: "Male Grooming Level 2",
      brand: "Engage",
      subBrand: "Engage",
    },
    {
      id: 13,
      category: "Foods",
      subCategory: "Foods Level 1",
      subCategoryL2: "Foods Level 2",
      brand: "Cureveda",
      subBrand: "Cureveda",
    },
    {
      id: 14,
      category: "Foods",
      subCategory: "Foods Level 1",
      subCategoryL2: "Foods Level 2",
      brand: "Raw Pressery",
      subBrand: "Raw Pressery",
    },
    {
      id: 15,
      category: "Foods",
      subCategory: "Foods Level 1",
      subCategoryL2: "Foods Level 2",
      brand: "Wingreen",
      subBrand: "Wingreen",
    },
    {
      id: 16,
      category: "Foods",
      subCategory: "Foods Level 1",
      subCategoryL2: "Foods Level 2",
      brand: "Zandu",
      subBrand: "Zandu",
    },
    {
      id: 17,
      category: "Hair Care",
      subCategory: "Hair Care Level 1",
      subCategoryL2: "Hair Care Level 2",
      brand: "Hair & Care",
      subBrand: "Hair & Care",
    },
    {
      id: 18,
      category: "Hair Care",
      subCategory: "Hair Care Level 1",
      subCategoryL2: "Hair Care Level 2",
      brand: "Nihar Naturals Hair Oil",
      subBrand: "Nihar Naturals Hair Oil",
    },
    {
      id: 19,
      category: "Hair Care",
      subCategory: "Hair Care Level 1",
      subCategoryL2: "Hair Care Level 2",
      brand: "Jataa",
      subBrand: "Jataa",
    },
    {
      id: 20,
      category: "Hair Care",
      subCategory: "Hair Care Level 1",
      subCategoryL2: "Hair Care Level 2",
      brand: "Parachute Advansed Onion",
      subBrand: "Parachute Advansed Onion",
    },
  ]);
}
